packages:
  - apps/*
  - packages/*
  - tools/*

ignoredBuiltDependencies:
  - '@nestjs/core'
  - bcrypt
  - msgpackr-extract
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
